services:
  - type: web
    name: hls-proxy
    env: php
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 index.php
    plan: free
    autoDeploy: true
    envVars:
      - key: PHP_VERSION
        value: 8.2
